export const appointmentRows = [
  {
    date: "Dec 11, 2025 2:30 pm",
    service: "Bikini Blitz Drip",
    duration: "1h",
    points: "120 Drips",
    status: "Approved",
  },
  {
    date: "Dec 5, 2025 12:00 pm",
    service: "Performance Drip",
    duration: "30m",
    points: "40 Drips",
    status: "Approved",
  },
  {
    date: "Dec 1, 2025 3:00 pm",
    service: "NAD+ Drip",
    duration: "1h",
    points: "180 Drips",
    status: "Approved",
  },
  {
    date: "Nov 26, 2025 10:45",
    service: "Autumn Restore",
    duration: "1h",
    points: "120 Drips",
    status: "Approved",
  },
  {
    date: "Nov 23, 2025 11:15",
    service: "Performance Drip",
    duration: "30m",
    points: "40 Drips",
    status: "Approved",
  },
  {
    date: "Nov 10, 2025 10:45",
    service: "Performance Drip",
    duration: "30m",
    points: "40 Drips",
    status: "Approved",
  },
  {
    date: "Oct 12, 2025 4:00 pm",
    service: "Hangover Cure Drip",
    duration: "1h",
    points: "110 Drips",
    status: "Approved",
  },
  {
    date: "Oct 05, 2025 4:00 pm",
    service: "Autumn Restore",
    duration: "1h",
    points: "120 Drips",
    status: "Approved",
  },
  {
    date: "Oct 01, 2025 4:00 pm",
    service: "Autumn Restore",
    duration: "1h",
    points: "120 Drips",
    status: "Approved",
  },
];
