export const treatmentCatalog = [
  { name: "Niagen Plus Drip - Medium Bag (500mg)", category: "IV Therapy", duration: "1 h", price: "$1,250.00" },
  { name: "Niagen Plus Drip - Small Bag (250mg)", category: "IV Therapy", duration: "1 h", price: "$800.00" },
  { name: "Nad+ Drip - Large Bag (750mg)", category: "IV Therapy", duration: "1 h", price: "$800.00" },
  { name: "Nad+ Drip - Medium Bag (500mg)", category: "IV Therapy", duration: "1 h", price: "$685.00" },
  { name: "Nad+ Drip - Small Bag (250mg)", category: "IV Therapy", duration: "1 h", price: "$545.00" },
  { name: "Autumn Restore Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$350.00" },
  { name: "Migraine Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Migraine Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Radiance Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Radiance Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Energy Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Energy Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Bikini Blitz Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Bikini Blitz Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Performance Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Performance Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Myers Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Myers Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Immunity Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Immunity Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Rejuvenate Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Rejuvenate Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Hangover Cure Drip - Large Bag (1000mL)", category: "IV Therapy", duration: "1 h", price: "$335.00" },
  { name: "Hangover Cure Drip - Small Bag (500mL)", category: "IV Therapy", duration: "1 h", price: "$275.00" },
  { name: "Hydration Drip (1000mL)", category: "IV Therapy", duration: "1 h 15 min", price: "$175.00" },
  { name: "Wolverine Stack - (BPC-157 • TB-500 • KPV • MGF)", category: "Peptide Wellness", duration: "30 min", price: "$150.00" },
  { name: "BPC-157 Therapy", category: "Peptide Wellness", duration: "30 min", price: "$150.00" },
  { name: "GHK-Cu Therapy", category: "Peptide Wellness", duration: "30 min", price: "$150.00" },
  { name: "CJC-1295 + Ipamorelin", category: "Peptide Wellness", duration: "30 min", price: "$150.00" },
  { name: "Melanotan II", category: "Peptide Wellness", duration: "30 min", price: "$150.00" },
  { name: "Vitamin B12 Injection", category: "Injections & Boosters", duration: "30 min", price: "$40.00" },
  { name: "Vitamin B Complex Injection", category: "Injections & Boosters", duration: "30 min", price: "$40.00" },
  { name: "Vitamin C Injection", category: "Injections & Boosters", duration: "30 min", price: "$40.00" },
  { name: "Glutathione Injection", category: "Injections & Boosters", duration: "30 min", price: "$40.00" },
  { name: "Testosterone Replacement Therapy (TRT)", category: "Testosterone", duration: "30 min", price: "$250.00" },
  { name: "Online Telehealth Consultations", category: "Online Telehealth Consultations", duration: "30 min", price: "$150.00" },
  { name: "Peptide Consultation", category: "Peptide Wellness", duration: "30 min", price: "$150.00" },
  { name: "NAD+ Boost 50mg", category: "IV Therapy", duration: "30 min", price: "$100.00" },
  { name: "NAD+ Injection 50mg", category: "IV Therapy", duration: "30 min", price: "$100.00" },
  { name: "Botox Consultation", category: "Botox", duration: "30 min", price: "$150.00" },
  { name: "Compression Boots (20 mins)", category: "Compression Boots", duration: "15 min", price: "$25.00" },
  { name: "Compression Boots (40 mins)", category: "Compression Boots", duration: "45 min", price: "$30.00" },
  { name: "Compression Boots (60 mins)", category: "Compression Boots", duration: "1 h", price: "$50.00" },
  { name: "Glutathione IV Drip (100mL)", category: "IV Therapy", duration: "45 min", price: "$175.00" },
];

const areaProductPriceMap = {
  "Niagen Plus Drip": "$800.00",
  "NAD+": "$545.00",
  "NAD+ Drip": "$545.00",
  "Autumn Restore": "$350.00",
  "Migraine Drip": "$275.00",
  "Radiance Drip": "$275.00",
  "Energy Drip": "$275.00",
  "Bikini Blitz Drip": "$275.00",
  "Performance Drip": "$275.00",
  Performance: "$275.00",
  "Myers Drip": "$275.00",
  "Immunity Drip": "$275.00",
  "Rejuvenate Drip": "$275.00",
  Rejuvenate: "$275.00",
  "Hangover Cure Drip": "$275.00",
  "Hangover Drip": "$275.00",
  Hangover: "$275.00",
  "Hydration Drip": "$175.00",
  "NYD+ Drip": "$545.00",
};

export function getAreaProductPrice(productTitle) {
  return areaProductPriceMap[productTitle] ?? null;
}
